# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

# Here you have to include your Twig extensions
services:
    app.twig_extensions.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    # This is our custom Twig extension
    # Here you can find information on how to define a custom Twig extension:
    # http://symfony.com/doc/current/templating/twig_extension.html
    app.twig.website:
        class: AppBundle\Twig\WebsiteTwigExtension
        tags:
            - { name: twig.extension }